name: Publish

on:
  workflow_dispatch:

  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    name: Publish to GH Pages

    steps:
      - name: Checkout site
        uses: actions/checkout@v2

      - name: Checkout 1.x docs
        uses: actions/checkout@master
        with:
          repository: hotwired-laravel/turbo-laravel
          ref: 1.x
          path: 1.x-src

      - name: Checkout 2.x docs
        uses: actions/checkout@master
        with:
          repository: hotwired-laravel/turbo-laravel
          ref: 2.x
          path: 2.x-src

      - name: Copy sources
        run: |
          cp -R 1.x-src/docs/ source/_v1
          cp -R 2.x-src/docs/ source/_docs

      - name: Install Dependencies
        run: |
          composer install
          npm install

      - name: Build
        run: |
          npm run prod

      - name: Add CNAME
        run: |
          echo "turbo-laravel.com" > build_production/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_production
