name: Publish

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    name: Publish to GH Pages

    steps:
      - name: Checkout site
        uses: actions/checkout@v2

      - name: Checkout 1.x docs
        uses: actions/checkout@master
        with:
          repository: hotwired-laravel/turbo-laravel
          ref: 1.x
          path: 1.x-src

      - name: Checkout 2.x docs
        uses: actions/checkout@master
        with:
          repository: hotwired-laravel/turbo-laravel
          ref: 2.x
          path: 2.x-src

      - name: Install Dependencies
        run: |
          composer install
          npm install

      - name: Copy sources
        run: |
          cp -R 1.x-src/docs/ source/_1.x
          cp -R 2.x-src/docs/ source/_2.x

      - name: Build
        run: |
          npm run prod

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_production
